name: C++ CI ubuntu

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.2.0'
    - name: C++ generation
      run: |
        mkdir bin
        cd bin
        cmake ../src -DCMAKE_PREFIX_PATH=%Qt6_DIR%
